// This file is automatically generated. Do not modify it.
// See the documentation for more information.

import { FirebaseOptions } from 'firebase/app';

// This is the value of the auto-provisioned FIREBASE_CONFIG environment variable.
// It will be automatically populated by Firebase App Hosting.
const firebaseConfigStr = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;

function getFirebaseConfig(): FirebaseOptions {
  if (!firebaseConfigStr) {
    throw new Error(
      'Firebase config not found. Check that the NEXT_PUBLIC_FIREBASE_CONFIG environment variable is set.'
    );
  }
  return JSON.parse(firebaseConfigStr);
}

export const firebaseConfig = getFirebaseConfig();
