// This file is automatically generated. Do not modify it.
// See the documentation for more information.

import { FirebaseOptions } from 'firebase/app';

// This is the value of the auto-provisioned FIREBASE_CONFIG environment variable.
// It will be automatically populated by Firebase App Hosting.
const firebaseConfigStr = process.env.NEXT_PUBLIC_FIREBASE_CONFIG;

function getFirebaseConfig(): FirebaseOptions {
  // Hard-coded config to bypass parsing issues.
  return {
    "projectId": "studio-4099315804-e80d6",
    "appId": "1:612900810099:web:215c7a85e31e9340f62906",
    "apiKey": "AIzaSyCLmBM-3rzFUsQe6Cko5AXZRcYAzY0Jxvw",
    "authDomain": "studio-4099315804-e80d6.firebaseapp.com",
    "measurementId": "",
    "messagingSenderId": "612900810099"
  };
}

export const firebaseConfig = getFirebaseConfig();
